### ISSUE TITLE
Using with Aternos via Replit

### ISSUE THREAD

**Issue by Fl1ckw1ck** [Stonley890/mc-console-bot#8]
I'm using Aternos to run my server and replit.com to run to the code. How would I put my server path using these? I'm not even sure if I can access my server.jar with Aternos. With replit i'm running it with the cloud. 
Would there be a way for the bot to start it from a URL/website link?

**Comment by Stonley890** [comment]
I don't think there's any way to make it work with Aternos. They keep their systems pretty locked down because they don't want people exploiting the auto-shutdown.
This really only works best when you are able to send terminal commands to your server (or is run locally on your own computer).

**Comment by ReedGraf** [comment]
This can't be used with Aternos. These projects are meant for Aternos but have a chance of not working due to lack of maintaining the code by the owner. I'd try them out:
[https://github.com/Mekolaos/Aternos-On-Discord](https://github.com/Mekolaos/Aternos-On-Discord)
[https://github.com/sleeyax/aternos-discord-bot](https://github.com/sleeyax/aternos-discord-bot)
